version: '3'
services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "8000:80"
    restart: always
    tty: true
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: adminer
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: test
  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
  db:
      image: mysql:8.0.33
      volumes:
        - dbdata:/var/lib/mysql
      restart: always
      ports:
      - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
        MYSQL_USER: adminer
        MYSQL_PASSWORD: root
volumes:
  dbdata: 


  
          